laravel/app/Http/routes.php
<?php

Route::get('/', ['as' => 'home', 'uses' => 'HomeController@index']);
Route::get('quem-somos', ['as' => 'quem-somos', 'uses' => 'QuemSomosController@index']);
Route::get('portfolio/{cat?}', ['as' => 'portfolio', 'uses' => 'PortfolioController@index']);
Route::get('portfolio/{cat}/galeria', ['as' => 'portfolio.show', 'uses' => 'PortfolioController@show']);
Route::get('orcamento', ['as' => 'orcamento', 'uses' => 'OrcamentoController@index']);
Route::post('orcamento', ['as' => 'orcamento.envio', 'uses' => 'OrcamentoController@envio']);
Route::get('promocoes', ['as' => 'promocoes', 'uses' => 'PromocoesController@index']);
Route::get('videos', ['as' => 'videos', 'uses' => 'VideosController@index']);
Route::get('workshops', ['as' => 'workshops', 'uses' => 'WorkshopsController@index']);
Route::get('workshops/{workshop}', ['as' => 'workshops.show', 'uses' => 'WorkshopsController@show']);
Route::get('depoimentos', ['as' => 'depoimentos', 'uses' => 'DepoimentosController@index']);
Route::get('contato', ['as' => 'contato', 'uses' => 'ContatoController@index']);


// Painel
Route::group(['prefix' => 'painel', 'namespace' => 'Painel', 'middleware' => 'auth'], function() {
    Route::get('/', ['as' => 'painel', 'uses' => 'HomeController@index']);

    Route::resource('banners', 'BannersController');
    Route::resource('quem-somos', 'QuemSomosController');
    // Route::resource('portfolio/categorias', 'PortfolioCategoriasController');
    Route::resource('portfolio', 'PortfolioController');
    Route::resource('portfolio.imagens', 'PortfolioImagensController');
    Route::resource('orcamentos', 'OrcamentosController');
    Route::resource('promocoes/video', 'PromocoesVideoController');
    Route::resource('promocoes', 'PromocoesController');
    Route::resource('videos', 'VideosController');
    Route::resource('workshops', 'WorkshopsController');
    // Route::resource('workshops.imagens', 'WorkshopsImagensController');
    Route::resource('depoimentos', 'DepoimentosController');
    Route::resource('contato', 'ContatoController');
    Route::resource('usuarios', 'UsuariosController');

    Route::post('order', 'HomeController@order');
    Route::get('logs', '\Rap2hpoutre\LaravelLogViewer\LogViewerController@index');
});


// Auth
Route::group(['prefix' => 'painel', 'namespace' => 'Auth'], function() {
    Route::get('login', ['as' => 'login', 'uses' => 'AuthController@getLogin']);
    Route::post('login', ['as' => 'auth', 'uses' => 'AuthController@postLogin']);
    Route::get('logout', ['as' => 'logout', 'uses' => 'AuthController@getLogout']);
});

laravel/app/Http/Controllers/Painel/BannersController.php
<?php

namespace App\Http\Controllers\Painel;

use Illuminate\Http\Request;

use App\Http\Requests;
use App\Http\Requests\BannerRequest;

use App\Http\Controllers\Controller;
use App\Models\Banner;
use App\Helpers\CropImage;

class BannersController extends Controller
{
    private $image_config = [
        'width'  => 2000,
        'height' => null,
        'upsize' => true,
        'path'   => 'assets/img/banners/'
    ];

    public function index()
    {
        $banners = Banner::ordenados()->get();

        return view('painel.banners.index', compact('banners'));
    }

    public function create()
    {
        return view('painel.banners.create');
    }

    public function store(BannerRequest $request)
    {
        try {

            $input = $request->all();
            $input['imagem'] = CropImage::make('imagem', $this->image_config);

            Banner::create($input);
            return redirect()->route('painel.banners.index')->with('success', 'Banner adicionado com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao adicionar banner: '.$e->getMessage()]);

        }
    }

    public function edit(Banner $banner)
    {
        return view('painel.banners.edit', compact('banner'));
    }

    public function update(BannerRequest $request, Banner $banner)
    {
        try {

            $input = array_filter($request->all(), 'strlen');
            if (isset($input['imagem'])) $input['imagem'] = CropImage::make('imagem', $this->image_config);

            $banner->update($input);
            return redirect()->route('painel.banners.index')->with('success', 'Banner alterado com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao alterar banner: '.$e->getMessage()]);

        }
    }

    public function destroy(Banner $banner)
    {
        try {

            $banner->delete();
            return redirect()->route('painel.banners.index')->with('success', 'Banner excluído com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao excluir banner: '.$e->getMessage()]);

        }
    }
}

laravel/app/Http/Controllers/Painel/ContatoController.php
<?php

namespace App\Http\Controllers\Painel;

use Illuminate\Http\Request;

use App\Http\Requests;
use App\Http\Requests\ContatoRequest;

use App\Http\Controllers\Controller;
use App\Models\Contato;

class ContatoController extends Controller
{
    public function index()
    {
        $contato = Contato::first();

        return view('painel.contato.index', compact('contato'));
    }

    public function update(ContatoRequest $request, Contato $contato)
    {
        try {

            $input = $request->all();

            $contato->update($input);
            return redirect()->route('painel.contato.index')->with('success', 'Página alterada com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao alterar página: '.$e->getMessage()]);

        }
    }
}

laravel/app/Http/Controllers/Painel/DepoimentosController.php
<?php

namespace App\Http\Controllers\Painel;

use Illuminate\Http\Request;

use App\Http\Requests;
use App\Http\Requests\DepoimentoRequest;

use App\Http\Controllers\Controller;
use App\Models\Depoimento;
use App\Helpers\CropImage;

class DepoimentosController extends Controller
{
    private $image_config = [
        'width'  => 450,
        'height' => 300,
        'path'   => 'assets/img/depoimentos/'
    ];

    public function index()
    {
        $depoimentos = Depoimento::ordenados()->get();

        return view('painel.depoimentos.index', compact('depoimentos'));
    }

    public function create()
    {
        return view('painel.depoimentos.create');
    }

    public function store(DepoimentoRequest $request)
    {
        try {

            $input = $request->all();
            $input['imagem'] = CropImage::make('imagem', $this->image_config);

            Depoimento::create($input);
            return redirect()->route('painel.depoimentos.index')->with('success', 'Depoimento adicionado com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao adicionar depoimento: '.$e->getMessage()]);

        }
    }

    public function edit(Depoimento $depoimento)
    {
        return view('painel.depoimentos.edit', compact('depoimento'));
    }

    public function update(DepoimentoRequest $request, Depoimento $depoimento)
    {
        try {

            $input = array_filter($request->all(), 'strlen');
            if (isset($input['imagem'])) $input['imagem'] = CropImage::make('imagem', $this->image_config);

            $depoimento->update($input);
            return redirect()->route('painel.depoimentos.index')->with('success', 'Depoimento alterado com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao alterar depoimento: '.$e->getMessage()]);

        }
    }

    public function destroy(Depoimento $depoimento)
    {
        try {

            $depoimento->delete();
            return redirect()->route('painel.depoimentos.index')->with('success', 'Depoimento excluído com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao excluir depoimento: '.$e->getMessage()]);

        }
    }
}

laravel/app/Http/Controllers/Painel/HomeController.php
<?php

namespace App\Http\Controllers\Painel;

use Illuminate\Http\Request;

use App\Http\Requests;
use App\Http\Controllers\Controller;

use DB;

class HomeController extends Controller
{

    public function index()
    {
        return view('painel.home');
    }

    public function order(Request $request)
    {
        if (!$request->ajax()) return false;

        $data  = $request->input('data');
        $table = $request->input('table');

        for ($i = 0; $i < count($data); $i++) {
            DB::table($table)->where('id', $data[$i])->update(array('ordem' => $i));
        }

        return json_encode($data);
    }

}

laravel/app/Http/Controllers/Painel/OrcamentosController.php
<?php

namespace App\Http\Controllers\Painel;

use Illuminate\Http\Request;

use App\Http\Requests;
use App\Http\Requests\OrcamentoRequest;

use App\Http\Controllers\Controller;
use App\Models\Orcamento;

class OrcamentosController extends Controller
{
    public function index()
    {
        $orcamentos = Orcamento::orderBy('id', 'DESC')->paginate(15);

        return view('painel.orcamentos.index', compact('orcamentos'));
    }

    public function show(Orcamento $orcamento)
    {
        $orcamento->update(['lido' => 1]);

        return view('painel.orcamentos.show', compact('orcamento'));
    }

    public function destroy(Orcamento $orcamento)
    {
        try {

            $orcamento->delete();
            return redirect()->route('painel.orcamentos.index')->with('success', 'Orçamento excluído com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao excluir orçamento: '.$e->getMessage()]);

        }
    }
}

laravel/app/Http/Controllers/Painel/PortfolioController.php
<?php

namespace App\Http\Controllers\Painel;

use Illuminate\Http\Request;

use App\Http\Requests;
use App\Http\Requests\PortfolioRequest;

use App\Http\Controllers\Controller;
use App\Models\Portfolio;

class PortfolioController extends Controller
{
    public function index(Request $request)
    {
        $categorias = Portfolio::ordenados()->get();

        return view('painel.portfolio.index', compact('categorias'));
    }

    public function create()
    {
        return view('painel.portfolio.create');
    }

    public function store(PortfolioRequest $request)
    {
        try {

            Portfolio::create($request->all());
            return redirect()->route('painel.portfolio.index')->with('success', 'Categoria adicionada com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao adicionar categoria: '.$e->getMessage()]);

        }
    }

    public function edit(Portfolio $categoria)
    {
        return view('painel.portfolio.edit', compact('categoria'));
    }

    public function update(PortfolioRequest $request, Portfolio $categoria)
    {
        try {

            $categoria->update($request->all());
            return redirect()->route('painel.portfolio.index')->with('success', 'Categoria alterada com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao alterar categoria: '.$e->getMessage()]);

        }
    }

    public function destroy(Portfolio $categoria)
    {
        try {

            $categoria->delete();
            return redirect()->route('painel.portfolio.index')->with('success', 'Categoria excluída com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao excluir categoria: '.$e->getMessage()]);

        }
    }
}

laravel/app/Http/Controllers/Painel/PortfolioImagensController.php
<?php

namespace App\Http\Controllers\Painel;

use Illuminate\Http\Request;

use App\Http\Requests;
use App\Http\Requests\PortfolioImagemRequest;

use App\Http\Controllers\Controller;
use App\Models\Portfolio;
use App\Models\PortfolioImagem;

use App\Helpers\CropImage;

class PortfolioImagensController extends Controller
{
    private $image_config = [
        [
            'width'  => 180,
            'height' => 180,
            'path'   => 'assets/img/portfolio/capa/'
        ],
        [
            'width'     => 90,
            'height'    => 90,
            'greyscale' => true,
            'path'      => 'assets/img/portfolio/thumbs/'
        ],
        [
            'width'     => 980,
            'height'    => 580,
            'galeria'   => true,
            'upsize'    => true,
            'watermark' => true,
            'path'      => 'assets/img/portfolio/'
        ]
    ];
    public function index(Portfolio $portfolio)
    {
        $imagens = PortfolioImagem::portfolio($portfolio->id)->ordenados()->get();

        return view('painel.portfolio.imagens.index', compact('imagens', 'portfolio'));
    }

    public function create(Portfolio $portfolio)
    {
        return view('painel.portfolio.imagens.create', compact('portfolio'));
    }

    public function store(Portfolio $portfolio, PortfolioImagemRequest $request)
    {
        try {

            $input = $request->all();
            $input['imagem'] = CropImage::make('imagem', $this->image_config);
            $input['portfolio_id'] = $portfolio->id;

            $imagem = PortfolioImagem::create($input);
            $view = view('painel.portfolio.imagens.imagem', compact('portfolio', 'imagem'))->render();

            return response()->json(['body' => $view]);

        } catch (\Exception $e) {

            return 'Erro ao adicionar imagem: '.$e->getMessage();

        }
    }

    public function destroy(Portfolio $portfolio, PortfolioImagem $imagem)
    {
        try {

            $imagem->delete();
            return redirect()->route('painel.portfolio.imagens.index', $portfolio)
                             ->with('success', 'Imagem excluída com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao excluir imagem: '.$e->getMessage()]);

        }
    }
}

laravel/app/Http/Controllers/Painel/PromocoesController.php
<?php

namespace App\Http\Controllers\Painel;

use Illuminate\Http\Request;

use App\Http\Requests;
use App\Http\Requests\PromocaoRequest;

use App\Http\Controllers\Controller;
use App\Models\Promocao;
use App\Helpers\CropImage;

class PromocoesController extends Controller
{
    private $image_config = [
        [
            'width'  => 800,
            'height' => null,
            'upsize' => true,
            'path'   => 'assets/img/promocoes/'
        ],
        [
            'width'  => 450,
            'height' => null,
            'path'   => 'assets/img/promocoes/thumbs/'
        ]
    ];

    public function index()
    {
        $promocoes = Promocao::ordenados()->get();

        return view('painel.promocoes.index', compact('promocoes'));
    }

    public function create()
    {
        return view('painel.promocoes.create');
    }

    public function store(PromocaoRequest $request)
    {
        try {

            $input = $request->all();
            $input['imagem'] = CropImage::make('imagem', $this->image_config);

            Promocao::create($input);
            return redirect()->route('painel.promocoes.index')->with('success', 'Promoção adicionada com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao adicionar promoção: '.$e->getMessage()]);

        }
    }

    public function edit(Promocao $promocao)
    {
        return view('painel.promocoes.edit', compact('promocao'));
    }

    public function update(PromocaoRequest $request, Promocao $promocao)
    {
        try {

            $input = array_filter($request->all(), 'strlen');
            if (isset($input['imagem'])) $input['imagem'] = CropImage::make('imagem', $this->image_config);

            $promocao->update($input);
            return redirect()->route('painel.promocoes.index')->with('success', 'Promoção alterada com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao alterar promoção: '.$e->getMessage()]);

        }
    }

    public function destroy(Promocao $promocao)
    {
        try {

            $promocao->delete();
            return redirect()->route('painel.promocoes.index')->with('success', 'Promoção excluída com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao excluir promoção: '.$e->getMessage()]);

        }
    }
}

laravel/app/Http/Controllers/Painel/PromocoesVideoController.php
<?php

namespace App\Http\Controllers\Painel;

use Illuminate\Http\Request;

use App\Http\Requests;
use App\Http\Requests\PromocoesVideoRequest;

use App\Http\Controllers\Controller;
use App\Models\PromocoesVideo;

class PromocoesVideoController extends Controller
{
    public function index()
    {
        $video = PromocoesVideo::first();

        return view('painel.promocoes.video', compact('video'));
    }

    public function update(PromocoesVideoRequest $request, PromocoesVideo $video)
    {
        try {

            $input = $request->all();

            $video->update($input);

            return redirect()->route('painel.promocoes.video.index')->with('success', 'Página alterada com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao alterar página: '.$e->getMessage()]);

        }
    }
}

laravel/resources/views/painel/common/flash.blade.php
@if(session('success'))
   <div class="alert alert-block alert-success">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        {!! session('success') !!}
    </div>
@endif

@if($errors->any())
    <div class="alert alert-block alert-danger">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        @foreach($errors->all() as $error)
        {!! $error !!}<br>
        @endforeach
    </div>
@endif

laravel/resources/views/painel/common/nav.blade.php
<ul class="nav navbar-nav" style="font-size: 14px">
    <li @if(str_is('painel.banners*', Route::currentRouteName())) class="active" @endif>
        <a href="{{ route('painel.banners.index') }}">Banners</a>
    </li>

    <li @if(str_is('painel.quem-somos*', Route::currentRouteName())) class="active" @endif>
        <a href="{{ route('painel.quem-somos.index') }}">Quem Somos</a>
    </li>

    <li @if(str_is('painel.portfolio*', Route::currentRouteName())) class="active" @endif>
        <a href="{{ route('painel.portfolio.index') }}">Portfolio</a>
    </li>

    <li @if(str_is('painel.orcamentos*', Route::currentRouteName())) class="active" @endif>
        <a href="{{ route('painel.orcamentos.index') }}">
        Orçamentos
        @if($orcamentos_nao_lidos >= 1)
        <span class="label label-success" style="margin-left:3px;">{{ $orcamentos_nao_lidos }}</span>
        @endif
        </a>
    </li>

    <li @if(str_is('painel.promocoes*', Route::currentRouteName())) class="active" @endif>
        <a href="{{ route('painel.promocoes.index') }}">Promoções</a>
    </li>

    <li @if(str_is('painel.videos*', Route::currentRouteName())) class="active" @endif>
        <a href="{{ route('painel.videos.index') }}">Vídeos</a>
    </li>

    <li @if(str_is('painel.workshops*', Route::currentRouteName())) class="active" @endif>
        <a href="{{ route('painel.workshops.index') }}">Workshops</a>
    </li>

    <li @if(str_is('painel.depoimentos*', Route::currentRouteName())) class="active" @endif>
        <a href="{{ route('painel.depoimentos.index') }}">Depoimentos</a>
    </li>

    <li @if(str_is('painel.contato*', Route::currentRouteName())) class="active" @endif>
        <a href="{{ route('painel.contato.index') }}">Contato</a>
    </li>

    <li class="dropdown @if(str_is('painel.usuarios*', Route::currentRouteName())) active @endif">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            <span class="glyphicon glyphicon-cog small" style="margin-right:3px"></span>
            <b class="caret"></b>
        </a>
        <ul class="dropdown-menu">
            <li><a href="{{ route('painel.usuarios.index') }}">Usuários</a></li>
            <li><a href="{{ route('logout') }}">Logout</a></li>
        </ul>
    </li>
</ul>

laravel/resources/views/painel/common/template.blade.php
<!doctype html>
<html lang="pt-BR">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <base href="{{ url() }}">

    <title>{{ config('site.name') }} - Painel Administrativo</title>

    <link rel="stylesheet" href="{{ asset('assets/painel/css/bootstrap.min.css') }}">
    <link rel="stylesheet" href="{{ asset('assets/painel/css/jquery-ui.min.css') }}">
</head>
<body>
    <nav class="navbar navbar-default navbar-static-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="{{ url() }}">{{ config('site.name') }}</a>
            </div>

            <div id="navbar" class="navbar-collapse collapse">
                @include('painel.common.nav')
            </div>
        </div>
    </nav>

    <div class="container" style="padding-bottom:30px;">
        @yield('content')
    </div>

    <script src="//ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
    <script>window.jQuery || document.write('<script src="{{ asset("assets/jquery.min.js") }}"><\/script>')</script>
    <script src="{{ asset('assets/painel/js/bootstrap.min.js') }}"></script>
    <script src="{{ asset('assets/painel/js/jquery-ui.min.js') }}"></script>
    <script src="{{ asset('assets/painel/js/bootbox.min.js') }}"></script>
    <script src="{{ asset('assets/painel/ckeditor/ckeditor.js') }}"></script>
    <script src="{{ asset('assets/painel/jquery-file-upload/js/jquery.fileupload.js') }}"></script>
    <script src="{{ asset('assets/painel/js/painel.js') }}"></script>
</body>
</html>